### ISSUE TITLE
Should all toasts default to using a solid background colour?

### ISSUE THREAD

**Issue by gregmsanderson** [irsyadadl/justd#336]
**Is your feature request related to a problem? Please describe.**
I noticed that the error toast is translucent and so can be hard to read if _other_ toasts are also present. The success toast doesn't have this issue.

**Describe the solution you'd like**
The error toast to use an opaque background colour: pink/red? I assume it has some alpha/opacity currently.

**Describe alternatives you've considered**
I _could_ just override it  ... but I assume that change would be lost when doing an update. Plus it might be nice for other users. Even if only for accessibility to ensure contrasting colours? Just a thought.

**Additional context**

https://github.com/user-attachments/assets/865fcbd8-346a-42c6-ab55-de5572f1f000

**Comment by irsyadadl** [comment]
What browser did you use? because as for me, success is also glass mode.

**Comment by gregmsanderson** [comment]
It's in latest Chrome and Firefox, on Mac.

The success is solid/opaque. The error, warning and info are all glass/translucent and so are affected by other toasts.

Out of interest, the original sonner demo has solid/opaque backgrounds for all four when using rich colours: https://sonner.emilkowal.ski/

**Comment by irsyadadl** [comment]
Thanks for the report, it used to not, also was checking the close button are not hidden by default. I will rework on this.

**Comment by irsyadadl** [comment]
Fixed on [d7e2e26](https://github.com/irsyadadl/justd/commit/d7e2e264b828e413806dfcfb8faa2093fc8c3fab).

**Comment by gregmsanderson** [comment]
Ah ... now _all_ the toasts have the glass/translucent style. Including the success one.

They are now consistent but that means the original issue remains: a _prior_ toast changes the background (due to the opacity) making them harder to read and muddying the colour. The original sonner does not have that problem.

Was that the intent? I can remove the toast opacity myself but just wondered. Thanks.
